import logging
from PyQt5 import QtCore, QtGui, QtWidgets
import threading
import time
import subprocess
import os

from PyQt5.QtCore import QTimer
from airtest.core.api import connect_device, touch
from airtest.core.cv import Template
logging.getLogger('airtest').setLevel(logging.ERROR)
def print_space(variable, spaces=4):
    print(' ' * spaces + str(variable))
def start_exe():    #启动模拟器
    while True:
        try:
            print('开始启动雷电模拟器')
            subprocess.Popen('E:\leidian\LDPlayer9\dnplayer.exe')
            #subprocess.Popen('%s' % set_address.get())
            print('启动成功')
            break
        except:
            print('未找到模拟器，5s后重新尝试启动')
            time.sleep(5)
def cnnect():   #连接模拟器
    global emulator_click
    emulator_click = 1
    a = 1
    while a > 0:  # 连接模拟器
        a = 0
        try:
            print('%d.开始尝试连接模拟器' % a)
            #os.popen('adb start-server')
            print_space('地址：android:// 127.0.0.1:5037')
            #print('地址：android:// %s' % str(set_ip.get()))
            connect_device('android://127.0.0.1:5037')
            #connect_device('android://%s'%set_ip.get())
            #subprocess.run(['adb', '-s', '127.0.0.1:21503', 'shell'])
            time.sleep(5)
            print_space('连接模拟器成功!!!')
            a = 0
        except:
            a += 1
            print_space('未连接到模拟器，5s后尝试重新连接')
            time.sleep(5)
def start_app():    #启动APP
    global emulator_click
    if emulator_click == 0:
        print('未连接模拟器')
        time.sleep(1)
        cnnect()
    while True:
        try:
            print_space('开始尝试启动游戏')
            '''if exists(Template(r"icon\tpl1719196072757.png", threshold=0.8, record_pos=(0.112, -0.519),
                           resolution=(414, 780))):
            print('游戏未启动，点击启动')'''
            touch(Template(r"icon\tpl1719196072757.png", record_pos=(0.112, -0.519), resolution=(414, 780)))
            print_space("启动成功，等待30秒启动时间...")
            time.sleep(30)
            print_space('启动完成')
            break
        except:
            print('启动失败，再次尝试')
def all_start():    #一键启动
    start_exe()
    print('等待30s以完成模拟器的启动')
    time.sleep(30)
    cnnect()
    print('等待10s以确保系统加载完成')
    time.sleep(10)
    start_app()
def start_simple(button_start_id):      #模拟器启动相关
    if button_start_id == 1:
        #start_exe_button.configure(text='启动模拟器', command=lambda: start_simple(1))
        # start_exe()
        '''启动模拟器线程'''
        threading.Thread(target=start_exe).start()  # threading.Thread(target=start_exe).join()
    elif button_start_id == 2:
        '''连接模拟器线程'''
        threading.Thread(target=cnnect).start()  # threading.Thread(target=cnnect).join()
    elif button_start_id == 3:
        #start_app_button.configure(text='再次启动app', command=lambda: start_simple(3))
        # start_app()
        '''启动app线程'''
        threading.Thread(target=start_app).start()  # threading.Thread(target=start_app).join()
    elif button_start_id == 4:
        '''一键启动线程'''
        threading.Thread(target=all_start).start()
    else:
        print_space('错误')

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(960, 540)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/log.png"))
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setAnimated(False)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 60, 461, 41))
        #self.frame.setStyleSheet("#frame{border:1px solid rgb(0,255,0)}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(10, 10, 91, 22))
        self.comboBox.setAutoFillBackground(False)
        #self.comboBox.setStyleSheet("background: transparent;")
        self.comboBox.setStyleSheet("QComboBox {\n"
                                    "    background-color: rgba(0, 0, 0, 0); /* 白色背景，150为透明度 */\n"
                                    "    border: 1px solid rgba(0, 255, 0); /* 边框样式 */\n"
                                    "}\n"
                                    "QComboBox QAbstractItemView {\n"
                                    "    background-color: transparent; /* 下拉列表背景透明度 */\n"
                                    "    border: 1px solid rgb(0,255,0); /* 下拉列表边框样式 */\n"
                                    "}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(130, 10, 221, 21))
        self.lineEdit.setMouseTracking(True)
        self.lineEdit.setAcceptDrops(True)
        self.lineEdit.setToolTip("")
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("QLineEdit {\n""    background: transparent;\n""    border: 1px solid rgba(0, 255, 0); /* 边框样式 */\n""}")
        self.lineEdit.setFrame(True)
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.save_simulator = QtWidgets.QPushButton(self.frame)
        self.save_simulator.setEnabled(True)
        self.save_simulator.setGeometry(QtCore.QRect(380, 10, 75, 23))
        self.save_simulator.setMouseTracking(False)
        self.save_simulator.setTabletTracking(False)
        self.save_simulator.setAcceptDrops(False)
        self.save_simulator.setToolTip("")
        self.save_simulator.setAutoFillBackground(False)
        self.save_simulator.setCheckable(False)
        self.save_simulator.setChecked(False)
        self.save_simulator.setAutoRepeat(False)
        self.save_simulator.setAutoExclusive(False)
        self.save_simulator.setAutoDefault(False)
        self.save_simulator.setDefault(False)
        self.save_simulator.setFlat(True)
        self.save_simulator.setStyleSheet("QPushButton {\n""border: 1px solid rgb(0,255,0); /* 边框样式 */\n"
                                      "}"
                                      "QPushButton:hover {\n"
                                      "background-color: rgba(0, 0, 0, 15); /* 编辑状态下的背景透明度 */\n"
                                      "}\n"
                                      "QPushButton:pressed {\n"
                                      "background-color: rgba(0, 0, 0, 80); /* 编辑状态下的背景透明度 */\n"
                                      "}\n")
        self.save_simulator.setObjectName("pushButton")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 160, 461, 41))
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_2.setBaseSize(QtCore.QSize(0, 0))
        self.frame_2.setMouseTracking(False)
        self.frame_2.setTabletTracking(False)
        self.frame_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.frame_2.setAcceptDrops(False)
        self.frame_2.setAutoFillBackground(False)
        #self.frame_2.setStyleSheet("#frame_2{border:1px solid rgb(0,255,0)}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.start_simulator = QtWidgets.QPushButton(self.frame_2)
        self.start_simulator.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.start_simulator.setFlat(True)
        self.start_simulator.setStyleSheet("border:1px solid rgb(0,255,0)")
        self.start_simulator.setObjectName("start_simulator")
        self.connect_simulator = QtWidgets.QPushButton(self.frame_2)
        self.connect_simulator.setGeometry(QtCore.QRect(130, 10, 75, 23))
        self.connect_simulator.setFlat(True)
        self.connect_simulator.setStyleSheet("border:1px solid rgb(0,255,0)")
        self.connect_simulator.setObjectName("connect_simulator")
        self.start_game = QtWidgets.QPushButton(self.frame_2)
        self.start_game.setGeometry(QtCore.QRect(260, 10, 75, 23))
        self.start_game.setAutoDefault(False)
        self.start_game.setDefault(False)
        self.start_game.setFlat(True)
        self.start_game.setStyleSheet("border:1px solid rgb(0,255,0)")
        self.start_game.setObjectName("start_game")
        self.simulator_start_all = QtWidgets.QPushButton(self.frame_2)
        self.simulator_start_all.setGeometry(QtCore.QRect(380, 10, 75, 23))
        self.simulator_start_all.setAutoDefault(False)
        self.simulator_start_all.setDefault(False)
        self.simulator_start_all.setFlat(True)
        self.simulator_start_all.setStyleSheet("border:1px solid rgb(0,255,0)")
        self.simulator_start_all.setObjectName("simulator_start_all")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 270, 461, 191))
        #self.frame_3.setStyleSheet("#frame_3{border:1px solid rgb(0,255,0)}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.select_text = QtWidgets.QLabel(self.frame_3)
        self.select_text.setGeometry(QtCore.QRect(10, 0, 81, 16))
        self.select_text.setObjectName("select_text")
        self.checkBox_help = QtWidgets.QCheckBox(self.frame_3)#互助
        self.checkBox_help.setGeometry(QtCore.QRect(20, 30, 71, 16))
        self.checkBox_help.setAutoFillBackground(False)
        self.checkBox_help.setStyleSheet("QCheckBox:indicator:checked {background-color: transparent;border:1px solid rgb(0,255,0)}"
        "QCheckBox:indicator {background-color: transparent;border:1px solid rgb(0,0,0)}")
        self.checkBox_help.setAutoRepeat(False)
        self.checkBox_help.setAutoExclusive(False)
        self.checkBox_help.setTristate(False)
        self.checkBox_help.setObjectName("checkBox_help")
        self.checkBox_XG = QtWidgets.QCheckBox(self.frame_3)#野怪
        self.checkBox_XG.setGeometry(QtCore.QRect(110, 30, 71, 16))
        self.checkBox_XG.setObjectName("checkBox_XG")
        self.checkBox_XG.setStyleSheet("background-color: transparent")
        self.checkBox_WM = QtWidgets.QCheckBox(self.frame_3)#冰原巨兽
        self.checkBox_WM.setGeometry(QtCore.QRect(200, 30, 71, 16))
        self.checkBox_WM.setObjectName("checkBox_WM")
        self.checkBox_npc = QtWidgets.QCheckBox(self.frame_3)#活动雪怪
        self.checkBox_npc.setGeometry(QtCore.QRect(290, 30, 71, 16))
        self.checkBox_npc.setObjectName("checkBox_npc")
        self.checkBox_Production = QtWidgets.QCheckBox(self.frame_3)#训练士兵
        self.checkBox_Production.setGeometry(QtCore.QRect(380, 30, 71, 16))
        self.checkBox_Production.setObjectName("checkBox_Production")
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_6.setGeometry(QtCore.QRect(380, 70, 71, 16))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_7.setGeometry(QtCore.QRect(290, 70, 71, 16))
        self.checkBox_7.setMouseTracking(True)
        self.checkBox_7.setTabletTracking(False)
        self.checkBox_7.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.checkBox_7.setStyleSheet("")
        self.checkBox_7.setCheckable(False)
        self.checkBox_7.setChecked(False)
        self.checkBox_7.setTristate(False)
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_8.setGeometry(QtCore.QRect(20, 70, 71, 16))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_9.setGeometry(QtCore.QRect(110, 70, 71, 16))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_10.setGeometry(QtCore.QRect(200, 70, 71, 16))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_13 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_13.setGeometry(QtCore.QRect(20, 110, 71, 16))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_14.setGeometry(QtCore.QRect(110, 110, 71, 16))
        self.checkBox_14.setObjectName("checkBox_14")
        self.select_all = QtWidgets.QPushButton(self.frame_3)
        self.select_all.setGeometry(QtCore.QRect(90, 150, 75, 23))
        self.select_all.setFlat(True)
        self.select_all.setObjectName("select_all")
        self.select_all.setStyleSheet("select_all:hover { background-color: blue; color: white; }")
        self.select_all.setStyleSheet("border:1px solid rgb(0,255,0)")
        self.select_unall = QtWidgets.QPushButton(self.frame_3)
        self.select_unall.setGeometry(QtCore.QRect(290, 150, 75, 23))
        self.select_unall.setFlat(True)
        self.select_unall.setObjectName("select_unall")
        self.select_unall.setStyleSheet("border:1px solid rgb(0,255,0)")
        self.select_stop = QtWidgets.QPushButton(self.frame_3)
        self.select_stop.setEnabled(True)
        self.select_stop.setGeometry(QtCore.QRect(190, 150, 75, 23))
        self.select_stop.setFlat(True)
        self.select_stop.setVisible(False)
        self.select_stop.setObjectName("select_stop")
        self.select_stop.setStyleSheet("border:1px solid rgb(0,255,0)")
        self.select_start = QtWidgets.QPushButton(self.frame_3)
        self.select_start.setEnabled(True)
        self.select_start.setGeometry(QtCore.QRect(190, 150, 75, 23))
        self.select_start.setWhatsThis("")
        self.select_start.setAutoFillBackground(False)
        self.select_start.setCheckable(False)
        self.select_start.setChecked(False)
        self.select_start.setFlat(True)
        self.select_start.setObjectName("select_start")
        self.select_start.setStyleSheet("border:1px solid rgb(0,255,0)")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setEnabled(False)
        self.listView.setGeometry(QtCore.QRect(-2, -1, 971, 553))
        self.listView.setAutoFillBackground(False)
        self.listView.setStyleSheet("background-image: url(:/icon/icon/11.png)")
        self.listView.setObjectName("listView")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(490, 60, 461, 191))
        #self.frame_4.setStyleSheet("#frame_4{border:1px solid rgb(0,255,0)}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.simple_title = QtWidgets.QLabel(self.frame_4)
        self.simple_title.setGeometry(QtCore.QRect(10, 0, 81, 21))
        self.simple_title.setObjectName("simple_title")
        self.radioButton_help = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_help.setGeometry(QtCore.QRect(20, 30, 71, 16))
        self.radioButton_help.setAutoFillBackground(False)
        self.radioButton_help.setStyleSheet("")
        self.radioButton_help.setCheckable(True)
        self.radioButton_help.setChecked(False)
        self.radioButton_help.setAutoRepeat(False)
        self.radioButton_help.setAutoExclusive(True)
        self.radioButton_help.setObjectName("radioButton_help")
        self.radioButton_XG = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_XG.setGeometry(QtCore.QRect(110, 30, 71, 16))
        self.radioButton_XG.setObjectName("radioButton_XG")
        self.radioButton_WM = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_WM.setGeometry(QtCore.QRect(200, 30, 71, 16))
        self.radioButton_WM.setObjectName("radioButton_WM")
        self.radioButton_npc = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_npc.setGeometry(QtCore.QRect(290, 30, 71, 16))
        self.radioButton_npc.setObjectName("radioButton_npc")
        self.radioButton_Production = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_Production.setGeometry(QtCore.QRect(380, 30, 71, 16))
        self.radioButton_Production.setObjectName("radioButton_Production")
        self.radioButton_11 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_11.setGeometry(QtCore.QRect(380, 70, 71, 16))
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_12.setGeometry(QtCore.QRect(290, 70, 71, 16))
        self.radioButton_12.setMouseTracking(True)
        self.radioButton_12.setTabletTracking(False)
        self.radioButton_12.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.radioButton_12.setStyleSheet("")
        self.radioButton_12.setCheckable(False)
        self.radioButton_12.setChecked(False)
        self.radioButton_12.setObjectName("radioButton_12")
        self.radioButton_build = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_build.setGeometry(QtCore.QRect(20, 70, 71, 16))
        self.radioButton_build.setObjectName("radioButton_build")
        self.radioButton_16 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_16.setGeometry(QtCore.QRect(110, 70, 71, 16))
        self.radioButton_16.setObjectName("radioButton_16")
        self.radioButton_17 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_17.setGeometry(QtCore.QRect(200, 70, 71, 16))
        self.radioButton_17.setObjectName("radioButton_17")
        self.radioButton_18 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_18.setGeometry(QtCore.QRect(20, 110, 71, 16))
        self.radioButton_18.setObjectName("radioButton_18")
        self.radioButton_ = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_.setGeometry(QtCore.QRect(110, 110, 71, 16))
        self.radioButton_.setObjectName("radioButton_")
        self.simple_stop = QtWidgets.QPushButton(self.frame_4)
        self.simple_stop.setEnabled(True)
        self.simple_stop.setVisible(False)
        self.simple_stop.setGeometry(QtCore.QRect(190, 150, 75, 23))
        self.simple_stop.setAutoExclusive(False)
        self.simple_stop.setDefault(False)
        self.simple_stop.setFlat(True)
        self.simple_stop.setProperty("Visible", False)
        self.simple_stop.setObjectName("simple_stop")
        self.simple_stop.setStyleSheet("border:1px solid rgb(0,255,0)")
        self.simple_start = QtWidgets.QPushButton(self.frame_4)
        self.simple_start.setEnabled(True)
        self.simple_start.setGeometry(QtCore.QRect(190, 150, 75, 23))
        self.simple_start.setWhatsThis("")
        self.simple_start.setAutoFillBackground(False)
        self.simple_start.setStyleSheet("")
        self.simple_start.setCheckable(False)
        self.simple_start.setChecked(False)
        self.simple_start.setAutoDefault(False)
        self.simple_start.setDefault(False)
        self.simple_start.setFlat(True)
        self.simple_start.setObjectName("simple_start")
        self.simple_start.setStyleSheet("border:1px solid rgb(0,255,0)")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(110, 0, 81, 21))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(190, 1, 51, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
                                    "background: transparent;\n"
                                    "border: 1px solid rgba(0, 255, 0)"
                                    "}")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(270, 0, 54, 21))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(300, 1, 31, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
                                    "background: transparent;\n"
                                    "border: 1px solid rgba(0, 255, 0)"
                                    "}")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_9.setGeometry(QtCore.QRect(380, 0, 75, 21))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.setFlat(True)
        self.pushButton_9.setStyleSheet("border:1px solid rgb(0,255,0)")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(490, 270, 461, 241))
        #self.frame_5.setStyleSheet("#frame_5{border:1px solid rgb(0,255,0)}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label.setObjectName("label")
        self.textEdit_out = QtWidgets.QTextEdit(self.frame_5)
        self.textEdit_out.setEnabled(True)
        self.textEdit_out.setGeometry(QtCore.QRect(10, 30, 441, 201))
        self.textEdit_out.setMouseTracking(True)
        self.textEdit_out.setTabletTracking(False)
        self.textEdit_out.setAcceptDrops(True)
        self.textEdit_out.setToolTip("")
        self.textEdit_out.setAutoFillBackground(False)
        self.textEdit_out.setStyleSheet("background: transparent;border:1px solid rgb(0,255,0)")
        self.textEdit_out.setTabChangesFocus(False)
        self.textEdit_out.setUndoRedoEnabled(False)
        self.textEdit_out.setReadOnly(True)
        self.textEdit_out.setOverwriteMode(False)
        self.textEdit_out.setAcceptRichText(True)
        #self.textEdit_out.setLineSpacing(1)
        #self.textBrowser.setOpenLinks(True)
        self.textEdit_out.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(890, 520, 71, 20))
        self.label_2.setObjectName("label_2")
        self.show_UI = QtWidgets.QPushButton(self.centralwidget)
        self.show_UI.setGeometry(QtCore.QRect(190, 520, 51, 23))
        self.show_UI.setFlat(True)
        self.show_UI.setObjectName("show_UI")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(60, 520, 61, 23))
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(130, 520, 41, 23))
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(370, 10, 231, 41))
        self.textEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.textEdit.setAutoFillBackground(False)
        self.textEdit.setStyleSheet("QTextEdit {\n"
"    background: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.textEdit.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit.setTabChangesFocus(False)
        self.textEdit.setUndoRedoEnabled(False)
        self.textEdit.setOverwriteMode(False)
        self.textEdit.setAcceptRichText(False)
        self.textEdit.setObjectName("textEdit")
        self.hide_UI = QtWidgets.QPushButton(self.centralwidget)
        self.hide_UI.setGeometry(QtCore.QRect(5, 520, 51, 23))
        self.hide_UI.setFlat(True)
        self.hide_UI.setObjectName("hide_UI")
        self.listView.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.frame_5.raise_()
        self.label_2.raise_()
        self.show_UI.raise_()
        self.show_UI.setVisible(False)
        self.show_UI.setGeometry(QtCore.QRect(5, 520, 51, 23))
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.textEdit.raise_()
        self.hide_UI.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.select_stop.clicked.connect(self.select_start.show) # type: ignore
        self.select_start.clicked.connect(self.select_stop.show) # type: ignore
        self.select_start.clicked.connect(self.select_start.hide) # type: ignore
        self.select_stop.clicked.connect(self.select_stop.hide) # type: ignore
        self.simple_start.clicked.connect(self.simple_start.hide) # type: ignore
        self.simple_start.clicked.connect(self.simple_stop.show) # type: ignore
        self.simple_stop.clicked.connect(self.simple_start.show) # type: ignore
        self.simple_stop.clicked.connect(self.simple_stop.hide) # type: ignore
        self.hide_UI.clicked.connect(self.hide_ui)  # type: ignore
        self.show_UI.clicked.connect(self.show_ui)  # type: ignore
        self.start_simulator.clicked.connect(lambda:start_simple(1))
        self.connect_simulator.clicked.connect(lambda: start_simple(2))
        self.start_game.clicked.connect(lambda: start_simple(3))
        self.simulator_start_all.clicked.connect(lambda: start_simple(4))
        self.select_all.clicked.connect(self.toggle_checkbox)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.comboBox.currentIndexChanged.connect(self.on_combobox_changed)
    def on_combobox_changed(self,index):
        if index == 0:
            self.lineEdit.setText('模拟器地址')
        if index == 1:
            self.lineEdit.setText('模拟器ip')

    def hide_ui(self):
        self.frame.setVisible(False)
        self.frame_2.setVisible(False)
        self.frame_3.setVisible(False)
        self.frame_4.setVisible(False)
        self.frame_5.setVisible(False)
        self.hide_UI.setVisible(False)
        self.show_UI.setVisible(True)
        self.textEdit.setVisible(False)
    def show_ui(self):
        self.frame.setVisible(True)
        self.frame_2.setVisible(True)
        self.frame_3.setVisible(True)
        self.frame_4.setVisible(True)
        self.frame_5.setVisible(True)
        self.hide_UI.setVisible(True)
        self.show_UI.setVisible(False)
        self.textEdit.setVisible(True)
    def toggle_checkbox(self):
        self.checkBox_help.setChecked(True)
        self.checkBox_XG.setChecked(True)
        self.checkBox_WM.setChecked(True)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "无尽冬日"))
        self.comboBox.setItemText(0, _translate("MainWindow", "模拟器路径"))
        self.comboBox.setItemText(1, _translate("MainWindow", "模拟器ip"))
        self.save_simulator.setText(_translate("MainWindow", "保存"))
        self.start_simulator.setText(_translate("MainWindow", "启动模拟器"))
        self.connect_simulator.setText(_translate("MainWindow", "连接模拟器"))
        self.start_game.setText(_translate("MainWindow", "启动游戏"))
        self.simulator_start_all.setText(_translate("MainWindow", "一键启动"))
        self.select_text.setText(_translate("MainWindow", "复选项（多选）"))
        self.checkBox_help.setText(_translate("MainWindow", "联盟互助"))
        self.checkBox_XG.setText(_translate("MainWindow", "世界野怪"))
        self.checkBox_WM.setText(_translate("MainWindow", "冰原巨兽"))
        self.checkBox_npc.setText(_translate("MainWindow", "活动雪怪"))
        self.checkBox_Production.setText(_translate("MainWindow", "训练士兵"))
        self.checkBox_6.setText(_translate("MainWindow", "探险奖励"))
        self.checkBox_7.setText(_translate("MainWindow", "治疗士兵"))
        self.checkBox_8.setText(_translate("MainWindow", "建筑升级"))
        self.checkBox_9.setText(_translate("MainWindow", "采集资源"))
        self.checkBox_10.setText(_translate("MainWindow", "巨熊活动"))
        self.checkBox_13.setText(_translate("MainWindow", "联盟捐赠"))
        self.checkBox_14.setText(_translate("MainWindow", "英雄招募"))
        self.select_all.setText(_translate("MainWindow", "全选"))
        self.select_unall.setText(_translate("MainWindow", "取消全选"))
        self.select_stop.setText(_translate("MainWindow", "停止"))
        self.select_start.setText(_translate("MainWindow", "开始"))
        self.simple_title.setText(_translate("MainWindow", "单选项（单选）"))
        self.radioButton_help.setText(_translate("MainWindow", "联盟互助"))
        self.radioButton_XG.setText(_translate("MainWindow", "世界野怪"))
        self.radioButton_WM.setText(_translate("MainWindow", "冰原巨兽"))
        self.radioButton_npc.setText(_translate("MainWindow", "活动雪怪"))
        self.radioButton_Production.setText(_translate("MainWindow", "训练士兵"))
        self.radioButton_11.setText(_translate("MainWindow", "探险奖励"))
        self.radioButton_12.setText(_translate("MainWindow", "治疗士兵"))
        self.radioButton_build.setText(_translate("MainWindow", "建筑升级"))
        self.radioButton_16.setText(_translate("MainWindow", "采集资源"))
        self.radioButton_17.setText(_translate("MainWindow", "巨熊活动"))
        self.radioButton_18.setText(_translate("MainWindow", "联盟捐赠"))
        self.radioButton_.setText(_translate("MainWindow", "英雄招募"))
        self.simple_stop.setText(_translate("MainWindow", "停止"))
        self.simple_start.setText(_translate("MainWindow", "开始"))
        self.label_3.setText(_translate("MainWindow", "执行间隔(秒):"))
        self.label_4.setText(_translate("MainWindow", "等级:"))
        self.pushButton_9.setText(_translate("MainWindow", "设置"))
        self.label.setText(_translate("MainWindow", "输出："))
        self.label_2.setText(_translate("MainWindow", "版本:1.2.2"))
        self.show_UI.setText(_translate("MainWindow", "显示UI"))
        self.pushButton_7.setText(_translate("MainWindow", "更新公告"))
        self.pushButton_8.setText(_translate("MainWindow", "帮助"))
        self.textEdit.setHtml(_translate("MainWindow",
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; \">请等待程序停止后再设置相关参数</span></p>\n"
        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; \">多选和单选不可同时执行</span></p></body>"))
        self.textEdit.setReadOnly(True)
        self.hide_UI.setText(_translate("MainWindow", "隐藏UI"))

    def write(self, text):
        # 将text写入QTextBrowser
        self.textEdit_out.insertPlainText(text)
        #设置写入时不换行
        #self.textBrowser.setLineWrapMode(0)
import icon_rc
import sys
from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5.QtGui import QPalette, QBrush, QPixmap

class MyApp(QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(MyApp, self).__init__(parent)
        self.setupUi(self)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    mainWindow = MyApp()
    # 重定向stdout和stderr
    sys.stdout = mainWindow
    sys.stderr = mainWindow
    mainWindow.show()
    sys.exit(app.exec_())